server:
  port: 8083
spring:
  application:
    name: ShipmentService

  #mysql database connection
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shipment-db?createDatabaseIfNotExist=true
    username: root
    password: root
  #hibernate/JPA
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
