server:
  port: 8082
spring:
  application:
    name: PaymentService
    #This is used to print the log colour full
  output:
    ansi:
      enabled: ALWAYS

  #mysql database connection
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/paymentDB?createDatabaseIfNotExist=true
    username: root
    password: root
 #hibernate/JPA
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      #H2 data base configuration
#  datasource:
#    url: jdbc:h2:file:~/data/paymentDB
#    driverClassName: org.h2.Driver
#    username: sa
#    password: password
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: create
#  h2:
#    console:
#      enabled: true
#      settings:
#        web-allow-others: true
#  sql:
#    init:
#      mode: ALWAYS

#axon:
#  eventhandling:
#    processors:
#      OrderProcessingSagaProcessor:
#        retry:
#          max-attempts: 3
#          initial-backoff: 100ms
#          max-backoff: 5s
#          multiplier: 2
#        mode: tracking
#        dlq:
#          enabled: true