server:
  port: 8081
spring:
  application:
    name: cab-driver-service
  #mysql database connection
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cab_driver?createDatabaseIfNotExist=true
    username: root
    password: root
  #hibernate/JPA
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

# Kafka configuration
  kafka:
    bootstrap-servers:
      - localhost:9092
    consumer:
      group-id: driver-group
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

